In [1]:
import pandas as pd

In [2]:
caminho = r'C:\EP04\2020\votacao_candidato_munzona_2020_BRASIL.csv'

In [3]:
df =pd.read_csv(caminho, delimiter=';', encoding='iso-8859-1', usecols=['NM_MUNICIPIO','SG_UF','SQ_CANDIDATO','DS_CARGO','DS_SITUACAO_CANDIDATURA','DS_DETALHE_SITUACAO_CAND','SG_PARTIDO','QT_VOTOS_NOMINAIS'])

In [4]:
df

,SG_UF,NM_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,DS_SITUACAO_CANDIDATURA,DS_DETALHE_SITUACAO_CAND,SG_PARTIDO,QT_VOTOS_NOMINAIS
0,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,29
1,AM,MANAUS,Vereador,40001182178,APTO,DEFERIDO,REPUBLICANOS,78
2,SP,CARDOSO,Vereador,250001266444,APTO,DEFERIDO,PSDB,11
3,SC,CRICIÚMA,Vereador,240000980207,APTO,DEFERIDO,PATRIOTA,2
4,MG,UBERABA,Vereador,130000757747,APTO,DEFERIDO,REPUBLICANOS,19
...,...,...,...,...,...,...,...,...
972163,SP,SÃO PAULO,Vereador,250000811391,APTO,DEFERIDO,PODE,16
972164,PR,MATO RICO,Vereador,160000732676,APTO,DEFERIDO,PSD,26
972165,SP,ARAÇOIABA DA SERRA,Vereador,250001035155,APTO,DEFERIDO,PSD,170
972166,RJ,RIO DE JANEIRO,Vereador,190001233804,APTO,DEFERIDO,PDT,8
972167,MG,UBERLÂNDIA,Vereador,130001011361,APTO,DEFERIDO,PSC,22

In [5]:
caminho = r'C:\EP04\2020\consulta_cand_2020_BRASIL.csv'

In [6]:
dfdescr =pd.read_csv(caminho, delimiter=';', encoding='iso-8859-1', usecols=['SQ_CANDIDATO','NR_IDADE_DATA_POSSE', 'DS_GENERO', 'DS_GRAU_INSTRUCAO','DS_COR_RACA','DS_OCUPACAO',])

In [7]:
dfdescr

,SQ_CANDIDATO,NR_IDADE_DATA_POSSE,DS_GENERO,DS_GRAU_INSTRUCAO,DS_COR_RACA,DS_OCUPACAO
0,80000952936,67,MASCULINO,SUPERIOR COMPLETO,PARDA,APOSENTADO (EXCETO SERVIDOR PÚBLICO)
1,250001139050,52,FEMININO,ENSINO FUNDAMENTAL INCOMPLETO,PARDA,DONA DE CASA
2,50001178649,37,FEMININO,ENSINO FUNDAMENTAL COMPLETO,SEM INFORMAÇÃO,OUTROS
3,130001023806,28,MASCULINO,ENSINO MÉDIO COMPLETO,PARDA,VEREADOR
4,90001021581,30,MASCULINO,ENSINO MÉDIO COMPLETO,BRANCA,OUTROS
...,...,...,...,...,...,...
557628,250001264623,60,MASCULINO,ENSINO FUNDAMENTAL INCOMPLETO,BRANCA,APOSENTADO (EXCETO SERVIDOR PÚBLICO)
557629,190001072004,62,MASCULINO,ENSINO MÉDIO COMPLETO,BRANCA,SERVIDOR PÚBLICO MUNICIPAL
557630,50001255977,60,MASCULINO,ENSINO MÉDIO COMPLETO,PARDA,OUTROS
557631,250001178910,56,MASCULINO,ENSINO FUNDAMENTAL INCOMPLETO,PRETA,VENDEDOR DE COMÉRCIO VAREJISTA E ATACADISTA
557632,170000920449,47,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,OUTROS

In [8]:
caminho = r'C:\EP04\IBGE_c.csv'

In [9]:
dflocal =pd.read_csv(caminho, delimiter=',', encoding='iso-8859-1', usecols=['nome','latitude','longitude'])

In [10]:
dflocal['NM_MUNICIPIO'] = dflocal['nome'].str.upper()

In [11]:
dflocal = dflocal.drop(columns=['nome'])

In [12]:
dflocal

      latitude  longitude         NM_MUNICIPIO
0    -16.75730   -49.4412      ABADIA DE GOIÁS
1    -18.48310   -47.3916  ABADIA DOS DOURADOS
2    -16.19700   -48.7057            ABADIÂNIA
3    -19.15510   -45.4444               ABAETÉ
4     -1.72183   -48.8788           ABAETETUBA
...        ...        ...                  ...
5565 -10.82300   -42.7245          XIQUE-XIQUE
5566  -8.07901   -37.1057              ZABELÃª
5567 -21.05060   -50.0552             ZACARIAS
5568  -3.27014   -45.6553              ZÉ DOCA
5569 -27.45210   -51.5520               ZORTÉA

[5570 rows x 3 columns]

In [13]:
df1 = pd.merge(df,dfdescr, on = "SQ_CANDIDATO")

In [14]:
df1

,SG_UF,NM_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,DS_SITUACAO_CANDIDATURA,DS_DETALHE_SITUACAO_CAND,SG_PARTIDO,QT_VOTOS_NOMINAIS,NR_IDADE_DATA_POSSE,DS_GENERO,DS_GRAU_INSTRUCAO,DS_COR_RACA,DS_OCUPACAO
0,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,29,58,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,EMPRESÁRIO
1,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,11,58,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,EMPRESÁRIO
2,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,3,58,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,EMPRESÁRIO
3,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,35,58,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,EMPRESÁRIO
4,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,5,58,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,EMPRESÁRIO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
972838,SP,PATROCÍNIO PAULISTA,Vereador,250001120544,APTO,DEFERIDO,CIDADANIA,126,34,FEMININO,SUPERIOR COMPLETO,PARDA,PROFESSOR E INSTRUTOR DE FORMAÇÃO PROFISSIONAL
972839,BA,TEIXEIRA DE FREITAS,Vereador,50000787574,APTO,DEFERIDO,PSB,30,34,MASCULINO,ENSINO MÉDIO COMPLETO,BRANCA,OUTROS
972840,MG,SÃO BRÁS DO SUAÇUÍ,Vereador,130000773784,APTO,DEFERIDO,PP,16,49,MASCULINO,ENSINO FUNDAMENTAL INCOMPLETO,PARDA,OUTROS
972841,PR,MATO RICO,Vereador,160000732676,APTO,DEFERIDO,PSD,26,48,FEMININO,ENSINO MÉDIO COMPLETO,PARDA,SERVIDOR PÚBLICO MUNICIPAL
972842,SP,ARAÇOIABA DA SERRA,Vereador,250001035155,APTO,DEFERIDO,PSD,170,61,MASCULINO,ENSINO FUNDAMENTAL INCOMPLETO,BRANCA,OUTROS

In [15]:
dfTotal = pd.merge(df1,dflocal, on ='NM_MUNICIPIO')

In [17]:
dfTotal.head(5)

,SG_UF,NM_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,DS_SITUACAO_CANDIDATURA,DS_DETALHE_SITUACAO_CAND,SG_PARTIDO,QT_VOTOS_NOMINAIS,NR_IDADE_DATA_POSSE,DS_GENERO,DS_GRAU_INSTRUCAO,DS_COR_RACA,DS_OCUPACAO,latitude,longitude
0,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,29,58,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,EMPRESÁRIO,-3.71664,-38.5423
1,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,11,58,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,EMPRESÁRIO,-3.71664,-38.5423
2,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,3,58,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,EMPRESÁRIO,-3.71664,-38.5423
3,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,35,58,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,EMPRESÁRIO,-3.71664,-38.5423
4,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,5,58,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,EMPRESÁRIO,-3.71664,-38.5423

In [22]:
Serie = dfTotal.groupby(['NM_MUNICIPIO','SG_UF','SQ_CANDIDATO','DS_CARGO','DS_SITUACAO_CANDIDATURA','DS_DETALHE_SITUACAO_CAND','SG_PARTIDO','DS_GENERO','DS_GRAU_INSTRUCAO','DS_OCUPACAO', 'DS_COR_RACA' ])['QT_VOTOS_NOMINAIS'].sum()

NM_MUNICIPIO     SG_UF  SQ_CANDIDATO  DS_CARGO  DS_SITUACAO_CANDIDATURA  DS_DETALHE_SITUACAO_CAND  SG_PARTIDO    DS_GENERO  DS_GRAU_INSTRUCAO              DS_OCUPACAO                                      DS_COR_RACA
ABADIA DE GOIÁS  GO     90000780341   Vereador  APTO                     DEFERIDO                  REPUBLICANOS  FEMININO   ENSINO MÉDIO COMPLETO          CORRETOR DE IMÓVEIS, SEGUROS, TÍTULOS E VALORES  PRETA           18
                        90000780342   Vereador  APTO                     DEFERIDO                  REPUBLICANOS  FEMININO   ENSINO FUNDAMENTAL INCOMPLETO  DONA DE CASA                                     PARDA            3
                        90000780343   Vereador  APTO                     DEFERIDO                  REPUBLICANOS  MASCULINO  ENSINO MÉDIO COMPLETO          CORRETOR DE IMÓVEIS, SEGUROS, TÍTULOS E VALORES  PARDA           93
                        90000780344   Vereador  APTO                     DEFERIDO                  REPUBLICANOS  MASCULINO  ENSINO MÉDIO INCOMPLETO        EMPRESÁRIO                                       PARDA          278
                        90000780345   Vereador  APTO                     DEFERIDO                  REPUBLICANOS  MASCULINO  SUPERIOR COMPLETO              PROFESSOR DE ENSINO MÉDIO                        PARDA           99
                                                                                                                                                                                                                          ...
ÁUREA            RS     210001250106  Vereador  APTO                     DEFERIDO                  PTB           MASCULINO  ENSINO FUNDAMENTAL INCOMPLETO  APOSENTADO (EXCETO SERVIDOR PÚBLICO)             BRANCA          58
                        210001250107  Vereador  APTO                     DEFERIDO                  PTB           MASCULINO  ENSINO FUNDAMENTAL INCOMPLETO  EMPRESÁRIO                                       BRANCA          47
                        210001250108  Vereador  APTO                     DEFERIDO                  PTB           FEMININO   ENSINO MÉDIO COMPLETO          SERVIDOR PÚBLICO MUNICIPAL                       BRANCA          25
                        210001250109  Vereador  APTO                     DEFERIDO                  PTB           MASCULINO  ENSINO FUNDAMENTAL INCOMPLETO  EMPRESÁRIO                                       BRANCA         106
                        210001250110  Vereador  APTO                     DEFERIDO                  PTB           MASCULINO  ENSINO FUNDAMENTAL INCOMPLETO  APOSENTADO (EXCETO SERVIDOR PÚBLICO)             BRANCA          64
Name: QT_VOTOS_NOMINAIS, Length: 494569, dtype: int64

In [26]:
dfx= Serie.to_frame()

In [28]:
dfx.query('SQ_CANDIDATO == "250001266824"')

                                                                                                                                                            QT_VOTOS_NOMINAIS
NM_MUNICIPIO SG_UF SQ_CANDIDATO DS_CARGO DS_SITUACAO_CANDIDATURA DS_DETALHE_SITUACAO_CAND SG_PARTIDO   DS_GENERO DS_GRAU_INSTRUCAO DS_OCUPACAO DS_COR_RACA
SÃO PAULO    SP    250001266824 Vereador APTO                    DEFERIDO                 REPUBLICANOS MASCULINO SUPERIOR COMPLETO ADVOGADO    BRANCA                     231

In [30]:
dfCandidatosZeroVoto = dfx.query('QT_VOTOS_NOMINAIS == 0 & DS_SITUACAO_CANDIDATURA=="APTO" & DS_DETALHE_SITUACAO_CAND== "DEFERIDO" & DS_CARGO=="Vereador"')

In [31]:
dfCandidatosZeroVoto

                                                                                                                                                                                                                    QT_VOTOS_NOMINAIS
NM_MUNICIPIO          SG_UF SQ_CANDIDATO DS_CARGO DS_SITUACAO_CANDIDATURA DS_DETALHE_SITUACAO_CAND SG_PARTIDO   DS_GENERO DS_GRAU_INSTRUCAO             DS_OCUPACAO                                    DS_COR_RACA
ABADIA DE GOIÁS       GO    90000818193  Vereador APTO                    DEFERIDO                 PSB          FEMININO  SUPERIOR INCOMPLETO           OUTROS                                         PARDA                        0
                            90001028251  Vereador APTO                    DEFERIDO                 PL           MASCULINO LÊ E ESCREVE                  OUTROS                                         PARDA                        0
ABADIÂNIA             GO    90001273386  Vereador APTO                    DEFERIDO                 MDB          FEMININO  SUPERIOR COMPLETO             FARMACÊUTICO                                   BRANCA                       0
ABAETETUBA            PA    140000854784 Vereador APTO                    DEFERIDO                 PSC          FEMININO  ENSINO FUNDAMENTAL INCOMPLETO OUTROS                                         PRETA                        0
                            140000933508 Vereador APTO                    DEFERIDO                 AVANTE       FEMININO  ENSINO MÉDIO COMPLETO         ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS PARDA                        0
...                                                                                                                                                                                                                               ...
ÁGUAS LINDAS DE GOIÁS GO    90001024963  Vereador APTO                    DEFERIDO                 PTC          FEMININO  ENSINO FUNDAMENTAL INCOMPLETO DONA DE CASA                                   PARDA                        0
                            90001143208  Vereador APTO                    DEFERIDO                 AVANTE       FEMININO  LÊ E ESCREVE                  OUTROS                                         PARDA                        0
ÁGUAS VERMELHAS       MG    130001074825 Vereador APTO                    DEFERIDO                 REPUBLICANOS FEMININO  ENSINO MÉDIO COMPLETO         ESTUDANTE, BOLSISTA, ESTAGIÁRIO E ASSEMELHADOS PARDA                        0
                            130001140018 Vereador APTO                    DEFERIDO                 PTC          FEMININO  ENSINO MÉDIO COMPLETO         OUTROS                                         PARDA                        0
ÁLVARES MACHADO       SP    250001169795 Vereador APTO                    DEFERIDO                 PT           FEMININO  ENSINO MÉDIO COMPLETO         APOSENTADO (EXCETO SERVIDOR PÚBLICO)           BRANCA                       0

[4442 rows x 1 columns]

In [38]:
Feminino = dfCandidatosZeroVoto.query('DS_GENERO=="FEMININO"').count()
Feminino

QT_VOTOS_NOMINAIS    3004
dtype: int64

In [37]:
Masculino = dfCandidatosZeroVoto.query('DS_GENERO=="MASCULINO"').count()
Masculino

QT_VOTOS_NOMINAIS    1438
dtype: int64