In [1]:
import pandas as pd

In [2]:
df =pd.read_csv('dados/resultados/votacao_candidato_munzona_2020_BRASIL.csv', delimiter=';', encoding='iso-8859-1', usecols=['NM_MUNICIPIO','SG_UF','SQ_CANDIDATO','DS_CARGO','DS_SITUACAO_CANDIDATURA','DS_DETALHE_SITUACAO_CAND','SG_PARTIDO','QT_VOTOS_NOMINAIS'])

In [3]:
## Agrupando os candidatos com o mesmo SQ
grouped = df.groupby('SQ_CANDIDATO')

In [4]:
## Somando os votos dos candidatos
b = grouped.sum()

In [5]:
b

              QT_VOTOS_NOMINAIS
SQ_CANDIDATO
10000641345                  77
10000641346                   0
10000641347                  23
10000641348                  43
10000641349                  59
...                         ...
270001274471                 23
270001274474                 14
270001274657                992
270001275304                116
270001276242                 14

[508369 rows x 1 columns]

In [6]:
type(b)

pandas.core.frame.DataFrame

In [7]:
##Agrupando o df que somou os votos com o df original
df1 = pd.merge(df,b, on = "SQ_CANDIDATO")

In [8]:
df1

,SG_UF,NM_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,DS_SITUACAO_CANDIDATURA,DS_DETALHE_SITUACAO_CAND,SG_PARTIDO,QT_VOTOS_NOMINAIS_x,QT_VOTOS_NOMINAIS_y
0,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,29,343
1,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,11,343
2,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,3,343
3,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,35,343
4,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,5,343
...,...,...,...,...,...,...,...,...,...
972163,SP,PATROCÍNIO PAULISTA,Vereador,250001120544,APTO,DEFERIDO,CIDADANIA,126,126
972164,BA,TEIXEIRA DE FREITAS,Vereador,50000787574,APTO,DEFERIDO,PSB,30,30
972165,MG,SÃO BRÁS DO SUAÇUÍ,Vereador,130000773784,APTO,DEFERIDO,PP,16,16
972166,PR,MATO RICO,Vereador,160000732676,APTO,DEFERIDO,PSD,26,26
972167,SP,ARAÇOIABA DA SERRA,Vereador,250001035155,APTO,DEFERIDO,PSD,170,170

In [9]:
## Retirando a coluna com os votos irreais
df1 = df1.drop(columns=['QT_VOTOS_NOMINAIS_x'])

In [10]:
df1

,SG_UF,NM_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,DS_SITUACAO_CANDIDATURA,DS_DETALHE_SITUACAO_CAND,SG_PARTIDO,QT_VOTOS_NOMINAIS_y
0,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,343
1,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,343
2,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,343
3,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,343
4,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,343
...,...,...,...,...,...,...,...,...
972163,SP,PATROCÍNIO PAULISTA,Vereador,250001120544,APTO,DEFERIDO,CIDADANIA,126
972164,BA,TEIXEIRA DE FREITAS,Vereador,50000787574,APTO,DEFERIDO,PSB,30
972165,MG,SÃO BRÁS DO SUAÇUÍ,Vereador,130000773784,APTO,DEFERIDO,PP,16
972166,PR,MATO RICO,Vereador,160000732676,APTO,DEFERIDO,PSD,26
972167,SP,ARAÇOIABA DA SERRA,Vereador,250001035155,APTO,DEFERIDO,PSD,170

In [11]:
## Retitrando os candidatos duplicados
df1 = df1.drop_duplicates()

In [12]:
df1

,SG_UF,NM_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,DS_SITUACAO_CANDIDATURA,DS_DETALHE_SITUACAO_CAND,SG_PARTIDO,QT_VOTOS_NOMINAIS_y
0,CE,FORTALEZA,Vereador,60000936791,APTO,DEFERIDO,PSDB,343
17,AM,MANAUS,Vereador,40001182178,APTO,DEFERIDO,REPUBLICANOS,883
30,SP,CARDOSO,Vereador,250001266444,APTO,DEFERIDO,PSDB,11
31,SC,CRICIÚMA,Vereador,240000980207,APTO,DEFERIDO,PATRIOTA,10
34,MG,UBERABA,Vereador,130000757747,APTO,DEFERIDO,REPUBLICANOS,23
...,...,...,...,...,...,...,...,...
972163,SP,PATROCÍNIO PAULISTA,Vereador,250001120544,APTO,DEFERIDO,CIDADANIA,126
972164,BA,TEIXEIRA DE FREITAS,Vereador,50000787574,APTO,DEFERIDO,PSB,30
972165,MG,SÃO BRÁS DO SUAÇUÍ,Vereador,130000773784,APTO,DEFERIDO,PP,16
972166,PR,MATO RICO,Vereador,160000732676,APTO,DEFERIDO,PSD,26
972167,SP,ARAÇOIABA DA SERRA,Vereador,250001035155,APTO,DEFERIDO,PSD,170

In [13]:
dfCandidatosZeroVoto = df1.query('QT_VOTOS_NOMINAIS_y == 0 & DS_SITUACAO_CANDIDATURA=="APTO" & DS_DETALHE_SITUACAO_CAND== "DEFERIDO" & DS_CARGO=="Vereador"')

In [14]:
dfCandidatosZeroVoto

,SG_UF,NM_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,DS_SITUACAO_CANDIDATURA,DS_DETALHE_SITUACAO_CAND,SG_PARTIDO,QT_VOTOS_NOMINAIS_y
96,SP,CUBATÃO,Vereador,250001242746,APTO,DEFERIDO,PMN,0
1001,CE,FORTALEZA,Vereador,60001098547,APTO,DEFERIDO,PL,0
2494,RJ,CASIMIRO DE ABREU,Vereador,190000928444,APTO,DEFERIDO,PV,0
9448,RN,MOSSORÓ,Vereador,200000967698,APTO,DEFERIDO,PSL,0
9774,MA,IMPERATRIZ,Vereador,100001211662,APTO,DEFERIDO,PSL,0
...,...,...,...,...,...,...,...,...
971840,RJ,PARAÍBA DO SUL,Vereador,190001107350,APTO,DEFERIDO,SOLIDARIEDADE,0
971865,AL,UNIÃO DOS PALMARES,Vereador,20001190952,APTO,DEFERIDO,PSL,0
971873,AM,NOVO ARIPUANÃ,Vereador,40001159424,APTO,DEFERIDO,PV,0
971948,BA,GUARATINGA,Vereador,50001274571,APTO,DEFERIDO,PROS,0
972081,BA,CENTRAL,Vereador,50001266306,APTO,DEFERIDO,PSC,0

In [15]:
## Gerando dados para os gráficos

In [16]:
## Candidatos com zero votos, por partido e municipio

PartidoMun = dfCandidatosZeroVoto.groupby(['NM_MUNICIPIO','SG_UF','SG_PARTIDO'])['SG_PARTIDO'].count()
PartidoMun

NM_MUNICIPIO     SG_UF  SG_PARTIDO
ABADIA DE GOIÁS  GO     PL              1
                        PSB             1
ABADIÂNIA        GO     MDB             1
ABAETETUBA       PA     AVANTE          1
                        PDT             2
                                       ..
ÁGUAS VERMELHAS  MG     REPUBLICANOS    1
ÁLVARES MACHADO  SP     PT              1
ÉRICO CARDOSO    BA     PSD             1
ÓBIDOS           PA     PC do B         1
ÓLEO             SP     PODE            1
Name: SG_PARTIDO, Length: 3546, dtype: int64

In [17]:
## Candidatos com zero votos, por partido

Partido = dfCandidatosZeroVoto.groupby(['SG_PARTIDO'])['SG_PARTIDO'].count()
Partido

SG_PARTIDO
AVANTE           165
CIDADANIA        155
DC                82
DEM              235
MDB              256
PATRIOTA         154
PC do B          112
PDT              166
PL               205
PMB               54
PMN               75
PODE             217
PP               206
PROS             167
PRTB             111
PSB              223
PSC              155
PSD              267
PSDB             231
PSL              214
PSOL              51
PT               173
PTB              169
PTC              144
PV               116
REDE              56
REPUBLICANOS     242
SOLIDARIEDADE    157
Name: SG_PARTIDO, dtype: int64

In [18]:
## Candidatos com zero votos, por estado
Estado = dfCandidatosZeroVoto.groupby(['SG_UF'])['SG_PARTIDO'].count()
Estado

SG_UF
AC     46
AL     97
AM    285
AP     54
BA    614
CE    181
ES     92
GO    148
MA    333
MG    468
MS     28
MT     55
PA    341
PB    167
PE    356
PI     16
PR    186
RJ    247
RN     63
RO     24
RR     23
RS     71
SC     41
SE     74
SP    486
TO     62
Name: SG_PARTIDO, dtype: int64

In [19]:
dfdescr =pd.read_csv('dados/candidatos/consulta_cand_2020_BRASIL.csv', delimiter=';', encoding='iso-8859-1', usecols=['SQ_CANDIDATO','NR_IDADE_DATA_POSSE', 'DS_GENERO', 'DS_GRAU_INSTRUCAO','DS_COR_RACA','DS_OCUPACAO',])

In [20]:
dfdescr.head(5)

,SQ_CANDIDATO,NR_IDADE_DATA_POSSE,DS_GENERO,DS_GRAU_INSTRUCAO,DS_COR_RACA,DS_OCUPACAO
0,210000883297,42,MASCULINO,ENSINO MÉDIO COMPLETO,BRANCA,AGRICULTOR
1,250001122285,49,MASCULINO,ENSINO MÉDIO COMPLETO,BRANCA,TÉCNICO DE QUÍMICA
2,250000983631,46,MASCULINO,ENSINO FUNDAMENTAL COMPLETO,BRANCA,MECÂNICO DE MANUTENÇÃO
3,200000980650,34,MASCULINO,ENSINO MÉDIO COMPLETO,BRANCA,VEREADOR
4,110001047590,51,MASCULINO,SUPERIOR COMPLETO,BRANCA,BIÓLOGO

In [21]:
dfCandidatosZeroVotonovo = pd.merge(dfCandidatosZeroVoto,dfdescr, on = "SQ_CANDIDATO")

In [22]:
dfCandidatosZeroVotonovo

,SG_UF,NM_MUNICIPIO,DS_CARGO,SQ_CANDIDATO,DS_SITUACAO_CANDIDATURA,DS_DETALHE_SITUACAO_CAND,SG_PARTIDO,QT_VOTOS_NOMINAIS_y,NR_IDADE_DATA_POSSE,DS_GENERO,DS_GRAU_INSTRUCAO,DS_COR_RACA,DS_OCUPACAO
0,SP,CUBATÃO,Vereador,250001242746,APTO,DEFERIDO,PMN,0,25,FEMININO,ENSINO MÉDIO COMPLETO,PARDA,OUTROS
1,CE,FORTALEZA,Vereador,60001098547,APTO,DEFERIDO,PL,0,49,FEMININO,ENSINO MÉDIO COMPLETO,BRANCA,ADMINISTRADOR
2,RJ,CASIMIRO DE ABREU,Vereador,190000928444,APTO,DEFERIDO,PV,0,30,FEMININO,SUPERIOR INCOMPLETO,BRANCA,OUTROS
3,RN,MOSSORÓ,Vereador,200000967698,APTO,DEFERIDO,PSL,0,20,FEMININO,ENSINO FUNDAMENTAL INCOMPLETO,PRETA,DONA DE CASA
4,MA,IMPERATRIZ,Vereador,100001211662,APTO,DEFERIDO,PSL,0,39,MASCULINO,ENSINO MÉDIO COMPLETO,PARDA,OUTROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4553,RJ,PARAÍBA DO SUL,Vereador,190001107350,APTO,DEFERIDO,SOLIDARIEDADE,0,42,MASCULINO,ENSINO MÉDIO COMPLETO,BRANCA,OUTROS
4554,AL,UNIÃO DOS PALMARES,Vereador,20001190952,APTO,DEFERIDO,PSL,0,35,MASCULINO,ENSINO MÉDIO COMPLETO,PARDA,OUTROS
4555,AM,NOVO ARIPUANÃ,Vereador,40001159424,APTO,DEFERIDO,PV,0,47,FEMININO,LÊ E ESCREVE,PARDA,OUTROS
4556,BA,GUARATINGA,Vereador,50001274571,APTO,DEFERIDO,PROS,0,26,FEMININO,ENSINO MÉDIO COMPLETO,PARDA,CANTOR E COMPOSITOR
4557,BA,CENTRAL,Vereador,50001266306,APTO,DEFERIDO,PSC,0,37,FEMININO,ENSINO MÉDIO INCOMPLETO,PARDA,TRABALHADOR RURAL

In [23]:
## Candidatos com zero votos, por Grau de instrução
Grau = dfCandidatosZeroVotonovo.groupby(['DS_GRAU_INSTRUCAO'])['DS_GRAU_INSTRUCAO'].count()
Grau

DS_GRAU_INSTRUCAO
ENSINO FUNDAMENTAL COMPLETO       706
ENSINO FUNDAMENTAL INCOMPLETO     737
ENSINO MÉDIO COMPLETO            1920
ENSINO MÉDIO INCOMPLETO           313
LÊ E ESCREVE                      264
SUPERIOR COMPLETO                 465
SUPERIOR INCOMPLETO               153
Name: DS_GRAU_INSTRUCAO, dtype: int64

In [24]:
## Candidatos com zero votos, Genero
Genero = dfCandidatosZeroVotonovo.groupby(['DS_GENERO'])['DS_GENERO'].count()
Genero

DS_GENERO
FEMININO     3075
MASCULINO    1483
Name: DS_GENERO, dtype: int64

In [25]:
## Candidatos com zero votos,Raça
Raça = dfCandidatosZeroVotonovo.groupby(['DS_COR_RACA'])['DS_COR_RACA'].count()
Raça

DS_COR_RACA
AMARELA             15
BRANCA            1609
INDÍGENA            50
PARDA             2343
PRETA              482
SEM INFORMAÇÃO      59
Name: DS_COR_RACA, dtype: int64

In [26]:
## Candidatos com zero votos por ocupação
Ocupação = dfCandidatosZeroVotonovo.groupby(['DS_OCUPACAO'])['DS_OCUPACAO'].count()
Ocupação

DS_OCUPACAO
ADMINISTRADOR                                                         53
ADVOGADO                                                              21
AGENTE ADMINISTRATIVO                                                 43
AGENTE DE SAÚDE E SANITARISTA                                          7
AGENTE DE SERVIÇOS FUNERÁRIOS E EMBALSAMADOR                           1
                                                                      ..
VENDEDOR DE COMÉRCIO VAREJISTA E ATACADISTA                           50
VENDEDOR PRACISTA, REPRESENTANTE, CAIXEIRO-VIAJANTE E ASSEMELHADOS    36
VEREADOR                                                              27
VETERINÁRIO                                                            3
VIGILANTE                                                             34
Name: DS_OCUPACAO, Length: 146, dtype: int64

In [27]:
import geopandas as gpd

In [28]:
dfLocal = gpd.read_file('dados/ShapefileIBGE/BR_Localidades_2010_v1.shp')

In [29]:
dfLocal

,ID,CD_GEOCODI,TIPO,CD_GEOCODB,NM_BAIRRO,CD_GEOCODS,NM_SUBDIST,CD_GEOCODD,NM_DISTRIT,CD_GEOCODM,...,NM_UF,CD_NIVEL,CD_CATEGOR,NM_CATEGOR,NM_LOCALID,LONG,LAT,ALT,GMRotation,geometry
0,1,110001505000001,URBANO,110001505006,Redondo,11000150500,None,110001505,ALTA FLORESTA D'OESTE,1100015,...,RONDÔNIA,1,05,CIDADE,ALTA FLORESTA D'OESTE,-61.999824,-11.935540,337.735719,0.0,POINT (-61.99982 -11.93554)
1,2,110001515000001,URBANO,None,None,11000151500,None,110001515,FILADÉLFIA D'OESTE,1100015,...,RONDÔNIA,2,15,VILA,FILADÉLFIA D'OESTE,-62.043898,-12.437239,215.244429,0.0,POINT (-62.04390 -12.43724)
2,3,110001520000001,URBANO,None,None,11000152000,None,110001520,IZIDOLÂNDIA,1100015,...,RONDÔNIA,2,20,VILA,IZIDOLÂNDIA,-62.175549,-12.601415,181.044807,0.0,POINT (-62.17555 -12.60142)
3,4,110001525000001,URBANO,None,None,11000152500,None,110001525,NOVA GEASE D'OESTE,1100015,...,RONDÔNIA,2,25,VILA,NOVA GEASE D'OESTE,-62.318650,-11.919792,191.576571,0.0,POINT (-62.31865 -11.91979)
4,5,110001530000001,URBANO,None,None,11000153000,None,110001530,ROLIM DE MOURA DO GUAPORÉ,1100015,...,RONDÔNIA,2,30,VILA,ROLIM DE MOURA DO GUAPORÉ,-62.276812,-13.079806,157.285277,0.0,POINT (-62.27681 -13.07981)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21881,21882,530010805180237,URBANO,None,None,53001080518,SAMAMBAIA,530010805,BRASÍLIA,5300108,...,DISTRITO FEDERAL,6,005,AUI,CONDOMÍNIO GUARAPARI,-48.238160,-15.939671,911.712363,0.0,POINT (-48.23816 -15.93967)
21882,21883,530010805180238,URBANO,None,None,53001080518,SAMAMBAIA,530010805,BRASÍLIA,5300108,...,DISTRITO FEDERAL,6,007,AUI,CONDOMÍNIO RESIDENCIAL NOVA BETÂNIA,-48.228517,-15.936009,926.632968,0.0,POINT (-48.22852 -15.93601)
21883,21884,530010805180314,URBANO,None,None,53001080518,SAMAMBAIA,530010805,BRASÍLIA,5300108,...,DISTRITO FEDERAL,6,006,AUI,CONDOMÍNIO SALOMÃO ELIAS,-48.241670,-15.939968,902.635257,0.0,POINT (-48.24167 -15.93997)
21884,21885,530010805200120,URBANO,None,None,53001080520,RECANTO DAS EMAS,530010805,BRASÍLIA,5300108,...,DISTRITO FEDERAL,6,003,AUI,CONDOMÍNIO SÃO FRANCISCO,-48.222924,-15.939726,921.346973,0.0,POINT (-48.22292 -15.93973)
21885,21886,530010805200123,URBANO,None,None,53001080520,RECANTO DAS EMAS,530010805,BRASÍLIA,5300108,...,DISTRITO FEDERAL,6,004,AUI,RESIDENCIAL BURITI I,-48.229109,-15.947606,953.389949,0.0,POINT (-48.22911 -15.94761)